//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AdminData
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AdamEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AdamEntities object using the connection string found in the 'AdamEntities' section of the application configuration file.
        /// </summary>
        public AdamEntities() : base("name=AdamEntities", "AdamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdamEntities object.
        /// </summary>
        public AdamEntities(string connectionString) : base(connectionString, "AdamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdamEntities object.
        /// </summary>
        public AdamEntities(EntityConnection connection) : base(connection, "AdamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblAcademicYear> tblAcademicYears
        {
            get
            {
                if ((_tblAcademicYears == null))
                {
                    _tblAcademicYears = base.CreateObjectSet<tblAcademicYear>("tblAcademicYears");
                }
                return _tblAcademicYears;
            }
        }
        private ObjectSet<tblAcademicYear> _tblAcademicYears;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblBatch> tblBatches
        {
            get
            {
                if ((_tblBatches == null))
                {
                    _tblBatches = base.CreateObjectSet<tblBatch>("tblBatches");
                }
                return _tblBatches;
            }
        }
        private ObjectSet<tblBatch> _tblBatches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCourse> tblCourses
        {
            get
            {
                if ((_tblCourses == null))
                {
                    _tblCourses = base.CreateObjectSet<tblCourse>("tblCourses");
                }
                return _tblCourses;
            }
        }
        private ObjectSet<tblCourse> _tblCourses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblExam> tblExams
        {
            get
            {
                if ((_tblExams == null))
                {
                    _tblExams = base.CreateObjectSet<tblExam>("tblExams");
                }
                return _tblExams;
            }
        }
        private ObjectSet<tblExam> _tblExams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblExamType> tblExamTypes
        {
            get
            {
                if ((_tblExamTypes == null))
                {
                    _tblExamTypes = base.CreateObjectSet<tblExamType>("tblExamTypes");
                }
                return _tblExamTypes;
            }
        }
        private ObjectSet<tblExamType> _tblExamTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSection> tblSections
        {
            get
            {
                if ((_tblSections == null))
                {
                    _tblSections = base.CreateObjectSet<tblSection>("tblSections");
                }
                return _tblSections;
            }
        }
        private ObjectSet<tblSection> _tblSections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblStudent> tblStudents
        {
            get
            {
                if ((_tblStudents == null))
                {
                    _tblStudents = base.CreateObjectSet<tblStudent>("tblStudents");
                }
                return _tblStudents;
            }
        }
        private ObjectSet<tblStudent> _tblStudents;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblAcademicYears EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblAcademicYears(tblAcademicYear tblAcademicYear)
        {
            base.AddObject("tblAcademicYears", tblAcademicYear);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblBatches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblBatches(tblBatch tblBatch)
        {
            base.AddObject("tblBatches", tblBatch);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCourses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCourses(tblCourse tblCourse)
        {
            base.AddObject("tblCourses", tblCourse);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblExams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblExams(tblExam tblExam)
        {
            base.AddObject("tblExams", tblExam);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblExamTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblExamTypes(tblExamType tblExamType)
        {
            base.AddObject("tblExamTypes", tblExamType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSections(tblSection tblSection)
        {
            base.AddObject("tblSections", tblSection);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblStudents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblStudents(tblStudent tblStudent)
        {
            base.AddObject("tblStudents", tblStudent);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectAdamModel", Name="tblAcademicYear")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblAcademicYear : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblAcademicYear object.
        /// </summary>
        /// <param name="acdmcYearId">Initial value of the AcdmcYearId property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static tblAcademicYear CreatetblAcademicYear(global::System.Int32 acdmcYearId, global::System.Boolean isActive)
        {
            tblAcademicYear tblAcademicYear = new tblAcademicYear();
            tblAcademicYear.AcdmcYearId = acdmcYearId;
            tblAcademicYear.IsActive = isActive;
            return tblAcademicYear;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcdmcYearId
        {
            get
            {
                return _AcdmcYearId;
            }
            set
            {
                if (_AcdmcYearId != value)
                {
                    OnAcdmcYearIdChanging(value);
                    ReportPropertyChanging("AcdmcYearId");
                    _AcdmcYearId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AcdmcYearId");
                    OnAcdmcYearIdChanged();
                }
            }
        }
        private global::System.Int32 _AcdmcYearId;
        partial void OnAcdmcYearIdChanging(global::System.Int32 value);
        partial void OnAcdmcYearIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AcdmcYear
        {
            get
            {
                return _AcdmcYear;
            }
            set
            {
                OnAcdmcYearChanging(value);
                ReportPropertyChanging("AcdmcYear");
                _AcdmcYear = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AcdmcYear");
                OnAcdmcYearChanged();
            }
        }
        private global::System.String _AcdmcYear;
        partial void OnAcdmcYearChanging(global::System.String value);
        partial void OnAcdmcYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectAdamModel", Name="tblBatch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblBatch : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblBatch object.
        /// </summary>
        /// <param name="batchID">Initial value of the BatchID property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static tblBatch CreatetblBatch(global::System.Int32 batchID, global::System.Boolean isActive)
        {
            tblBatch tblBatch = new tblBatch();
            tblBatch.BatchID = batchID;
            tblBatch.IsActive = isActive;
            return tblBatch;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BatchID
        {
            get
            {
                return _BatchID;
            }
            set
            {
                if (_BatchID != value)
                {
                    OnBatchIDChanging(value);
                    ReportPropertyChanging("BatchID");
                    _BatchID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BatchID");
                    OnBatchIDChanged();
                }
            }
        }
        private global::System.Int32 _BatchID;
        partial void OnBatchIDChanging(global::System.Int32 value);
        partial void OnBatchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BatchCode
        {
            get
            {
                return _BatchCode;
            }
            set
            {
                OnBatchCodeChanging(value);
                ReportPropertyChanging("BatchCode");
                _BatchCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BatchCode");
                OnBatchCodeChanged();
            }
        }
        private global::System.String _BatchCode;
        partial void OnBatchCodeChanging(global::System.String value);
        partial void OnBatchCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BatchName
        {
            get
            {
                return _BatchName;
            }
            set
            {
                OnBatchNameChanging(value);
                ReportPropertyChanging("BatchName");
                _BatchName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BatchName");
                OnBatchNameChanged();
            }
        }
        private global::System.String _BatchName;
        partial void OnBatchNameChanging(global::System.String value);
        partial void OnBatchNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateofCreation
        {
            get
            {
                return _DateofCreation;
            }
            set
            {
                OnDateofCreationChanging(value);
                ReportPropertyChanging("DateofCreation");
                _DateofCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateofCreation");
                OnDateofCreationChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateofCreation;
        partial void OnDateofCreationChanging(Nullable<global::System.DateTime> value);
        partial void OnDateofCreationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectAdamModel", Name="tblCourse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCourse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCourse object.
        /// </summary>
        /// <param name="courseID">Initial value of the CourseID property.</param>
        public static tblCourse CreatetblCourse(global::System.Int32 courseID)
        {
            tblCourse tblCourse = new tblCourse();
            tblCourse.CourseID = courseID;
            return tblCourse;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                if (_CourseID != value)
                {
                    OnCourseIDChanging(value);
                    ReportPropertyChanging("CourseID");
                    _CourseID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CourseID");
                    OnCourseIDChanged();
                }
            }
        }
        private global::System.Int32 _CourseID;
        partial void OnCourseIDChanging(global::System.Int32 value);
        partial void OnCourseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseCode
        {
            get
            {
                return _CourseCode;
            }
            set
            {
                OnCourseCodeChanging(value);
                ReportPropertyChanging("CourseCode");
                _CourseCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseCode");
                OnCourseCodeChanged();
            }
        }
        private global::System.String _CourseCode;
        partial void OnCourseCodeChanging(global::System.String value);
        partial void OnCourseCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseName
        {
            get
            {
                return _CourseName;
            }
            set
            {
                OnCourseNameChanging(value);
                ReportPropertyChanging("CourseName");
                _CourseName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseName");
                OnCourseNameChanged();
            }
        }
        private global::System.String _CourseName;
        partial void OnCourseNameChanging(global::System.String value);
        partial void OnCourseNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateofCreation
        {
            get
            {
                return _DateofCreation;
            }
            set
            {
                OnDateofCreationChanging(value);
                ReportPropertyChanging("DateofCreation");
                _DateofCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateofCreation");
                OnDateofCreationChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateofCreation;
        partial void OnDateofCreationChanging(Nullable<global::System.DateTime> value);
        partial void OnDateofCreationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectAdamModel", Name="tblExam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblExam : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblExam object.
        /// </summary>
        /// <param name="examID">Initial value of the ExamID property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static tblExam CreatetblExam(global::System.Int32 examID, global::System.Boolean isActive)
        {
            tblExam tblExam = new tblExam();
            tblExam.ExamID = examID;
            tblExam.IsActive = isActive;
            return tblExam;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExamID
        {
            get
            {
                return _ExamID;
            }
            set
            {
                if (_ExamID != value)
                {
                    OnExamIDChanging(value);
                    ReportPropertyChanging("ExamID");
                    _ExamID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ExamID");
                    OnExamIDChanged();
                }
            }
        }
        private global::System.Int32 _ExamID;
        partial void OnExamIDChanging(global::System.Int32 value);
        partial void OnExamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExamCode
        {
            get
            {
                return _ExamCode;
            }
            set
            {
                OnExamCodeChanging(value);
                ReportPropertyChanging("ExamCode");
                _ExamCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExamCode");
                OnExamCodeChanged();
            }
        }
        private global::System.String _ExamCode;
        partial void OnExamCodeChanging(global::System.String value);
        partial void OnExamCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExamNAme
        {
            get
            {
                return _ExamNAme;
            }
            set
            {
                OnExamNAmeChanging(value);
                ReportPropertyChanging("ExamNAme");
                _ExamNAme = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExamNAme");
                OnExamNAmeChanged();
            }
        }
        private global::System.String _ExamNAme;
        partial void OnExamNAmeChanging(global::System.String value);
        partial void OnExamNAmeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ExamTypeID
        {
            get
            {
                return _ExamTypeID;
            }
            set
            {
                OnExamTypeIDChanging(value);
                ReportPropertyChanging("ExamTypeID");
                _ExamTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExamTypeID");
                OnExamTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ExamTypeID;
        partial void OnExamTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnExamTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Instructions
        {
            get
            {
                return _Instructions;
            }
            set
            {
                OnInstructionsChanging(value);
                ReportPropertyChanging("Instructions");
                _Instructions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Instructions");
                OnInstructionsChanged();
            }
        }
        private global::System.String _Instructions;
        partial void OnInstructionsChanging(global::System.String value);
        partial void OnInstructionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                OnCourseIDChanging(value);
                ReportPropertyChanging("CourseID");
                _CourseID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CourseID");
                OnCourseIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CourseID;
        partial void OnCourseIDChanging(Nullable<global::System.Int32> value);
        partial void OnCourseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Duration;
        partial void OnDurationChanging(Nullable<global::System.TimeSpan> value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateofCreation
        {
            get
            {
                return _DateofCreation;
            }
            set
            {
                OnDateofCreationChanging(value);
                ReportPropertyChanging("DateofCreation");
                _DateofCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateofCreation");
                OnDateofCreationChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateofCreation;
        partial void OnDateofCreationChanging(Nullable<global::System.DateTime> value);
        partial void OnDateofCreationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Passmark
        {
            get
            {
                return _Passmark;
            }
            set
            {
                OnPassmarkChanging(value);
                ReportPropertyChanging("Passmark");
                _Passmark = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Passmark");
                OnPassmarkChanged();
            }
        }
        private Nullable<global::System.Decimal> _Passmark;
        partial void OnPassmarkChanging(Nullable<global::System.Decimal> value);
        partial void OnPassmarkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectAdamModel", Name="tblExamType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblExamType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblExamType object.
        /// </summary>
        /// <param name="examTypeID">Initial value of the ExamTypeID property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static tblExamType CreatetblExamType(global::System.Int32 examTypeID, global::System.Boolean isActive)
        {
            tblExamType tblExamType = new tblExamType();
            tblExamType.ExamTypeID = examTypeID;
            tblExamType.IsActive = isActive;
            return tblExamType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExamTypeID
        {
            get
            {
                return _ExamTypeID;
            }
            set
            {
                if (_ExamTypeID != value)
                {
                    OnExamTypeIDChanging(value);
                    ReportPropertyChanging("ExamTypeID");
                    _ExamTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ExamTypeID");
                    OnExamTypeIDChanged();
                }
            }
        }
        private global::System.Int32 _ExamTypeID;
        partial void OnExamTypeIDChanging(global::System.Int32 value);
        partial void OnExamTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExamTypeName
        {
            get
            {
                return _ExamTypeName;
            }
            set
            {
                OnExamTypeNameChanging(value);
                ReportPropertyChanging("ExamTypeName");
                _ExamTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExamTypeName");
                OnExamTypeNameChanged();
            }
        }
        private global::System.String _ExamTypeName;
        partial void OnExamTypeNameChanging(global::System.String value);
        partial void OnExamTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectAdamModel", Name="tblSection")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSection : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSection object.
        /// </summary>
        /// <param name="sectionId">Initial value of the SectionId property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static tblSection CreatetblSection(global::System.Int32 sectionId, global::System.Boolean isActive)
        {
            tblSection tblSection = new tblSection();
            tblSection.SectionId = sectionId;
            tblSection.IsActive = isActive;
            return tblSection;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SectionId
        {
            get
            {
                return _SectionId;
            }
            set
            {
                if (_SectionId != value)
                {
                    OnSectionIdChanging(value);
                    ReportPropertyChanging("SectionId");
                    _SectionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SectionId");
                    OnSectionIdChanged();
                }
            }
        }
        private global::System.Int32 _SectionId;
        partial void OnSectionIdChanging(global::System.Int32 value);
        partial void OnSectionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SectionName
        {
            get
            {
                return _SectionName;
            }
            set
            {
                OnSectionNameChanging(value);
                ReportPropertyChanging("SectionName");
                _SectionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SectionName");
                OnSectionNameChanged();
            }
        }
        private global::System.String _SectionName;
        partial void OnSectionNameChanging(global::System.String value);
        partial void OnSectionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectAdamModel", Name="tblStudent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblStudent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblStudent object.
        /// </summary>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static tblStudent CreatetblStudent(global::System.Int32 studentId, global::System.Boolean isActive)
        {
            tblStudent tblStudent = new tblStudent();
            tblStudent.StudentId = studentId;
            tblStudent.IsActive = isActive;
            return tblStudent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                if (_StudentId != value)
                {
                    OnStudentIdChanging(value);
                    ReportPropertyChanging("StudentId");
                    _StudentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StudentId");
                    OnStudentIdChanged();
                }
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdmissionNo
        {
            get
            {
                return _AdmissionNo;
            }
            set
            {
                OnAdmissionNoChanging(value);
                ReportPropertyChanging("AdmissionNo");
                _AdmissionNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AdmissionNo");
                OnAdmissionNoChanged();
            }
        }
        private global::System.String _AdmissionNo;
        partial void OnAdmissionNoChanging(global::System.String value);
        partial void OnAdmissionNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fname
        {
            get
            {
                return _Fname;
            }
            set
            {
                OnFnameChanging(value);
                ReportPropertyChanging("Fname");
                _Fname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fname");
                OnFnameChanged();
            }
        }
        private global::System.String _Fname;
        partial void OnFnameChanging(global::System.String value);
        partial void OnFnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mname
        {
            get
            {
                return _Mname;
            }
            set
            {
                OnMnameChanging(value);
                ReportPropertyChanging("Mname");
                _Mname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mname");
                OnMnameChanged();
            }
        }
        private global::System.String _Mname;
        partial void OnMnameChanging(global::System.String value);
        partial void OnMnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lname
        {
            get
            {
                return _Lname;
            }
            set
            {
                OnLnameChanging(value);
                ReportPropertyChanging("Lname");
                _Lname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lname");
                OnLnameChanged();
            }
        }
        private global::System.String _Lname;
        partial void OnLnameChanging(global::System.String value);
        partial void OnLnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Dob
        {
            get
            {
                return _Dob;
            }
            set
            {
                OnDobChanging(value);
                ReportPropertyChanging("Dob");
                _Dob = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dob");
                OnDobChanged();
            }
        }
        private Nullable<global::System.DateTime> _Dob;
        partial void OnDobChanging(Nullable<global::System.DateTime> value);
        partial void OnDobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactNo
        {
            get
            {
                return _ContactNo;
            }
            set
            {
                OnContactNoChanging(value);
                ReportPropertyChanging("ContactNo");
                _ContactNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactNo");
                OnContactNoChanged();
            }
        }
        private global::System.String _ContactNo;
        partial void OnContactNoChanging(global::System.String value);
        partial void OnContactNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MobileNo
        {
            get
            {
                return _MobileNo;
            }
            set
            {
                OnMobileNoChanging(value);
                ReportPropertyChanging("MobileNo");
                _MobileNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MobileNo");
                OnMobileNoChanged();
            }
        }
        private global::System.String _MobileNo;
        partial void OnMobileNoChanging(global::System.String value);
        partial void OnMobileNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GuardianName
        {
            get
            {
                return _GuardianName;
            }
            set
            {
                OnGuardianNameChanging(value);
                ReportPropertyChanging("GuardianName");
                _GuardianName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GuardianName");
                OnGuardianNameChanged();
            }
        }
        private global::System.String _GuardianName;
        partial void OnGuardianNameChanging(global::System.String value);
        partial void OnGuardianNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GuardianContact
        {
            get
            {
                return _GuardianContact;
            }
            set
            {
                OnGuardianContactChanging(value);
                ReportPropertyChanging("GuardianContact");
                _GuardianContact = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GuardianContact");
                OnGuardianContactChanged();
            }
        }
        private global::System.String _GuardianContact;
        partial void OnGuardianContactChanging(global::System.String value);
        partial void OnGuardianContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CommnAddress
        {
            get
            {
                return _CommnAddress;
            }
            set
            {
                OnCommnAddressChanging(value);
                ReportPropertyChanging("CommnAddress");
                _CommnAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CommnAddress");
                OnCommnAddressChanged();
            }
        }
        private global::System.String _CommnAddress;
        partial void OnCommnAddressChanging(global::System.String value);
        partial void OnCommnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PermAddress
        {
            get
            {
                return _PermAddress;
            }
            set
            {
                OnPermAddressChanging(value);
                ReportPropertyChanging("PermAddress");
                _PermAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PermAddress");
                OnPermAddressChanged();
            }
        }
        private global::System.String _PermAddress;
        partial void OnPermAddressChanging(global::System.String value);
        partial void OnPermAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailID
        {
            get
            {
                return _EmailID;
            }
            set
            {
                OnEmailIDChanging(value);
                ReportPropertyChanging("EmailID");
                _EmailID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailID");
                OnEmailIDChanged();
            }
        }
        private global::System.String _EmailID;
        partial void OnEmailIDChanging(global::System.String value);
        partial void OnEmailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    
    }

    #endregion

    
}
